name: Test
on: 
  push:
    branches: [ main ]

jobs:
  RunE2ETest:
    runs-on: ubuntu-latest

    steps:
      - name: Invoke workflow in another repo with inputs
        uses: benc-uk/workflow-dispatch@v1
        with:
           workflow: tests.yml
           repo: djpotes/playwright_examples
           token: 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
